aras_visual_servo:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  gantry_position_controller:
    type: effort_controllers/JointPositionController
    joint: gantry
    pid: {p: 15000, i: 5, d: 400, i_clamp: 1000.0}
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: J1
    pid: {p: 3000, i: 40, d: 40, i_clamp: 1000.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: J2
    pid: {p: 7000, i: 1000, d: 165, i_clamp: 1000.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: J3
    pid: {p: 4000, i: 200, d: 0, i_clamp: 1000.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: J5
    pid: {p: 3500, i: 150, d: 0, i_clamp: 1000.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: J6
    pid: {p: 70, i: 2, d: 0, i_clamp: 1000.0}
